version: '3.7'

services:
    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: opensea
    redis:
        image: redis:6.2.7
        ports:
            - '6379:6379'

volumes:
    mysql-data:
