version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: opensea

volumes:
  mysql-data:
